### ISSUE TITLE
Sub display

### ISSUE THREAD

**Issue by Koeseb** [d0p3t/SubNotifier#8]
So I just notice that only the resubs shows in the log and also it shows all custom messagas.

Is it possible to show first sub and also only the message which was choosen?
Kinda hard to read everything

pic: http://prntscr.com/glq32q

**Comment by d0p3t** [comment]
That's not the log, that is console output. As for console output, There are some inconsistencies. I'll be fixing them.

logs can be found in `./logs/`

**Comment by d0p3t** [comment]
I've updated the console output in the latest commit 6542bd3

It will now print any json in a more structured way. I've also removed the console output of all custom resubscription messages. This was in there by mistake.

With `enableDebug: true`
![image](https://i.imgur.com/4nNgsIX.png)

This issue is now resolved.

Closed!
